<a href="https://colab.research.google.com/github/kovyakov/Sketchbook/blob/master/Aula_03_Coleta_com_Selenium.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
#Coleta com Selenium
#Classificação Campeonato Brasileiro GE

In [ ]:
#Instalação de Ferramentas
!pip install selenium

In [2]:
!apt-get update
!apt-get install chromium-chromedriver

In [ ]:
!cp /usr/lib/chromium-browser/chromedriver /usr/bin

In [10]:
import sys
sys.path.insert(0, "/user/lib/chromium-driver")

from selenium import webdriver

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--headless")
chrome_options.add_argument("--no-sandbox")
chrome_options.add_argument("--disable-dev-shm-usage")

wd = webdriver.Chrome("chromedriver", options = chrome_options)
wd.get("https://ge.globo.com/futebol/brasileirao-serie-a/")

In [ ]:
table_points = wd.find_element_by_class_name("tabela__pontos")
table_teams = wd.find_elements_by_class_name("classificacao__equipes--nome")

In [30]:
import pandas as pd
from io import StringIO

content = StringIO(table_points.text)
table_points = pd.read_csv(content, sep=" ")
table_points.index =  [t.text for t in table_teams]
del table_points["ÚLT."]
del table_points["JOGOS"]

In [31]:
table_points

                P  J  V  E  D  GP  GC  SG     %
Corinthians    12  5  4  0  1   8   4   4  80.0
Santos         10  5  3  1  1  10   4   6  66.7
Avaí           10  5  3  1  1   6   6   0  66.7
América-MG      9  5  3  0  2   7   6   1  60.0
Bragantino      8  5  2  2  1   8   4   4  53.3
São Paulo       8  5  2  2  1   9   6   3  53.3
Atlético-MG     8  5  2  2  1   8   6   2  53.3
Botafogo        8  5  2  2  1   7   6   1  53.3
Internacional   8  5  2  2  1   4   4   0  53.3
Coritiba        7  5  2  1  2  10   8   2  46.7
Cuiabá          7  5  2  1  2   4   6  -2  46.7
Athletico-PR    6  5  2  0  3   2   6  -4  40.0
Palmeiras       6  5  1  3  1   7   5   2  40.0
Flamengo        5  5  1  2  2   4   4   0  33.3
Fluminense      5  5  1  2  2   4   5  -1  33.3
Goiás           5  5  1  2  2   6   9  -3  33.3
Ceará           3  4  1  0  3   4   7  -3  25.0
Juventude       3  5  0  3  2   5   9  -4  20.0
Atlético-GO     3  5  0  3  2   3   8  -5  20.0
Fortaleza       1  4  0  1  3   2   5  -3   8.3